dist: jammy
language: python
python:
  - "3.11"

services:
  - postgresql

before_script:
  - sudo service postgresql start
  - sleep 3
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'postgres';" -U postgres
  - export DJANGO_SETTINGS_MODULE=core.settings
  - export DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db
  - python manage.py migrate

install:
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage coveralls

script:
  - . venv/bin/activate
  - coverage run --source='.' manage.py test
  - coveralls --verbose

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    all_branches: true
