# Generated by Django 5.2.7 on 2025-10-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companydocument",
            name="num_chunks",
        ),
        migrations.AddField(
            model_name="companydocument",
            name="extracted_text",
            field=models.TextField(blank=True, help_text="Extracted text from PDF"),
        ),
        migrations.AlterField(
            model_name="companydocument",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("CODING", "Coding Questions"),
                    ("BEHAVIORAL", "Behavioral Questions"),
                    ("SYSTEM_DESIGN", "System Design Questions"),
                    ("PRODUCT_SENSE", "Product Sense Cases"),
                    ("ANALYTICAL", "Analytical & Strategy Questions"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="CompanyChunk",
        ),
    ]
