# Generated by Django 5.2.7 on 2025-10-11 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("amazon", "Amazon"),
                            ("microsoft", "Microsoft"),
                        ],
                        max_length=50,
                    ),
                ),
                ("job_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "resume_fit_score",
                    models.IntegerField(
                        blank=True, help_text="Score out of 100", null=True
                    ),
                ),
                (
                    "resume_analysis",
                    models.TextField(
                        blank=True, help_text="AI-generated analysis", null=True
                    ),
                ),
                (
                    "resume_suggestions",
                    models.TextField(
                        blank=True, help_text="AI-generated suggestions", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("user",),
                        name="unique_active_session_per_user",
                    )
                ],
            },
        ),
    ]
