# Generated by Django 5.2.7 on 2025-10-11 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_codinground'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDesignRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_question', models.TextField(help_text='Base question retrieved from RAG')),
                ('generated_question', models.JSONField(blank=True, help_text='Generated system design question with evaluation criteria', null=True)),
                ('user_answer', models.TextField(blank=True, help_text='User submitted design answer')),
                ('evaluation_result', models.JSONField(blank=True, help_text='AI evaluation results', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='codinground',
            name='question_number',
            field=models.IntegerField(default=1, help_text='Question number (1 or 2)'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='coding_q1_completed',
            field=models.BooleanField(default=False, help_text='Coding Question 1 completed'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='coding_q2_completed',
            field=models.BooleanField(default=False, help_text='Coding Question 2 completed'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_analysis',
            field=models.TextField(blank=True, help_text='Comprehensive final analysis', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='overall_readiness_score',
            field=models.IntegerField(blank=True, help_text='Overall readiness score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='system_design_completed',
            field=models.BooleanField(default=False, help_text='System Design completed'),
        ),
        migrations.AlterField(
            model_name='codinground',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_rounds', to='interviews.interviewsession'),
        ),
        migrations.AddConstraint(
            model_name='codinground',
            constraint=models.UniqueConstraint(fields=('session', 'question_number'), name='unique_question_per_session'),
        ),
        migrations.AddField(
            model_name='systemdesignround',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_design_round', to='interviews.interviewsession'),
        ),
    ]
