# Generated by Django 5.2.7 on 2025-10-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0004_interviewsession_behavioral_resume_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="analytical_strategy_completed",
            field=models.BooleanField(
                default=False, help_text="Analytical + Strategy completed"
            ),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="product_sense_completed",
            field=models.BooleanField(
                default=False, help_text="Product Sense completed"
            ),
        ),
        migrations.CreateModel(
            name="AnalyticalStrategyRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_question",
                    models.TextField(help_text="Base question retrieved from RAG"),
                ),
                (
                    "generated_question",
                    models.JSONField(
                        blank=True,
                        help_text="Generated analytical/strategy question with evaluation criteria",
                        null=True,
                    ),
                ),
                (
                    "user_answer",
                    models.TextField(blank=True, help_text="User submitted answer"),
                ),
                (
                    "evaluation_result",
                    models.JSONField(
                        blank=True, help_text="AI evaluation results", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytical_strategy_round",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSenseRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_case",
                    models.TextField(help_text="Base case retrieved from RAG"),
                ),
                (
                    "generated_case",
                    models.JSONField(
                        blank=True,
                        help_text="Generated product sense case with evaluation criteria",
                        null=True,
                    ),
                ),
                (
                    "user_answer",
                    models.TextField(blank=True, help_text="User submitted answer"),
                ),
                (
                    "evaluation_result",
                    models.JSONField(
                        blank=True, help_text="AI evaluation results", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_sense_round",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
