# Generated by Django 5.2.7 on 2025-11-25 19:17

import interviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0005_interviewsession_analytical_strategy_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemdesignround",
            name="design_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional architecture diagram or design drawing",
                null=True,
                upload_to=interviews.models.system_design_image_upload_path,
            ),
        ),
    ]
