# Generated by Django 5.2.7 on 2025-12-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0006_systemdesignround_design_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewsession",
            name="company",
            field=models.CharField(max_length=50),
        ),
    ]
